"""Shared architectural constants."""

ROOT_AGENT_ID = "tailmate.root"
PUBLIC_API_VERSION = "v1"
PUBLIC_API_PREFIX = f"/{PUBLIC_API_VERSION}"
PUBLIC_QUERY_PLATFORM = "web"
ACTIVE_DOG_ID_ATTRIBUTE_KEY = "active_dog_id"
PUBLIC_USER_REGISTER_PATH = f"{PUBLIC_API_PREFIX}/users/register"
PUBLIC_USER_ACTIVATE_PATH = f"{PUBLIC_API_PREFIX}/users/activate"
PUBLIC_USER_DELETE_PATH = f"{PUBLIC_API_PREFIX}/users/<user_id>"
PUBLIC_USER_EXPORT_PATH = f"{PUBLIC_API_PREFIX}/users/<user_id>/export"
PUBLIC_USER_CONNECTIONS_PATH = f"{PUBLIC_API_PREFIX}/users/connections/<platform>"
PUBLIC_AGENT_QUERY_PATH = f"{PUBLIC_API_PREFIX}/agent/query"
INTERNAL_KB_CHUNKS_PATH = "/kb/chunks"
INTERNAL_KB_CHUNK_PATH = "/kb/chunks/<chunk_id>"
INTERNAL_KB_CHUNK_IMPORT_PATH = "/kb/chunks/import"
SUPPORTED_USER_CONNECTION_PLATFORMS = frozenset(
    {"web", "telegram", "slack", "messenger"}
)
REQUEST_ID_HEADER = "X-Tailmate-Request-Id"
TRACE_ID_HEADER = "X-Trace-Id"
TRACEPARENT_METADATA_KEY = "traceparent"
TRACESTATE_METADATA_KEY = "tracestate"
PREFERRED_LOCALE_ATTRIBUTE_KEY = "preferred_locale"
TURN_DEBUG_METADATA_KEY = "turn_debug"
KNOWLEDGE_BASE_RESULT_METADATA_KEY = "knowledge_base"
TRUSTED_USER_ID_HEADER = "X-Tailmate-User-Id"
DOG_PROFILE_SKILL_ID = "dog_profile"
DOG_PROFILE_CREATE_TOOL_ID = "dog_profile.create"
DOG_PROFILE_ENRICH_TOOL_ID = "dog_profile.enrich"
DOG_PROFILE_RESULT_METADATA_KEY = "dog_profile"
STRIP_METADATA_SKILL_ID = "strip_metadata"
STRIP_METADATA_TOOL_ID = "strip_metadata.upload"
STRIP_METADATA_REQUEST_METADATA_KEY = "strip_metadata_request"
STRIP_METADATA_RESULT_METADATA_KEY = "strip_metadata"
