"""add_media_assets_table_for_strip_metadata"""

from alembic import op
import sqlalchemy as sa


revision = '46ecbdc4202a'
down_revision = '5e6e5005b32c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('media_id', sa.String(length=36), nullable=False),
    sa.Column('dog_id', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('resource_kind', sa.String(length=64), nullable=False),
    sa.Column('media_kind', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('logical_path', sa.String(length=1024), nullable=False),
    sa.Column('media_ref', sa.String(length=2048), nullable=False),
    sa.Column('sanitization_method', sa.String(length=64), nullable=False),
    sa.Column('sanitization_status', sa.String(length=32), server_default='sanitized', nullable=False),
    sa.Column('metadata_stripped', sa.Boolean(), server_default=sa.text('(true)'), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('media_id'),
    sa.UniqueConstraint('logical_path'),
    sa.UniqueConstraint('media_ref')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # WARNING: downgrade drops media_assets records and media metadata references.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media_assets')
    # ### end Alembic commands ###
