"""initial_runtime_tables"""

from alembic import op
import sqlalchemy as sa


revision = '5e6e5005b32c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_sessions',
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('turns', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('attributes', sa.JSON(), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # WARNING: downgrade drops conversation_sessions and all persisted turn history.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_sessions')
    # ### end Alembic commands ###
